### ISSUE TITLE
А почему вы решили не добавлять возможность задать статусы?

### ISSUE THREAD

**Issue by kirgus** [gam6itko/ozon-seller#11]
https://github.com/gam6itko/ozon-seller/blob/853539785aceb3880c077c985763378f4efac3b9/src/Service/Posting/FbsService.php#L22
![image](https://user-images.githubusercontent.com/47494681/72795959-90f0bb00-3c4f-11ea-849c-77667b3ceb28.png)

**Comment by gam6itko** [comment]
@kirgus Возможно, на момент прочтения мной документации, этофо фильтра не было в описании. Я реализую поддержку `status`, то сигнатура метода изменится.

**Comment by gam6itko** [comment]
@kirgus изменения будут в версии v0.2.3 для перехода используйте версию 0.2@dev
