### ISSUE TITLE
New method

### ISSUE THREAD

**Issue by animkaTT** [gam6itko/ozon-seller#17]
Please add a new method [/v2/category/attribute/values](https://cb-api.ozonru.me/apiref/ru/#t-title_attribute-_values) in [CategoryService.php](https://github.com/gam6itko/ozon-seller/blob/336798e377ed124f39a756d753c8f787f64e9756/src/Service/V2/CategoryService.php)

**Comment by gam6itko** [comment]
@animkaTT done. Now you can test it.
