### ISSUE TITLE
Некорректная обработка ответа печати маркировок

### ISSUE THREAD

**Issue by animkaTT** [gam6itko/ozon-seller#18]
В методе packageLabel [FbsService.php#L129](https://github.com/gam6itko/ozon-seller/blob/abc68ae0b2d901e07897580cdf6e80d32d934a57/src/Service/V2/Posting/FbsService.php#L129)   обработка идет так же как и для других методов - предполагая что в ответе JSON, но в ответе pdf файл https://cb-api.ozonru.me/apiref/ru/#t-fbs_package_label (тоже самое и для метода /v2/posting/fbs/act/get-pdf - https://cb-api.ozonru.me/apiref/ru/#t-section_postings_fbs_act_title).

**Comment by gam6itko** [comment]
@animkaTT К сожалению у меня нет заказов FBS на которых я смог бы протестировать этот функционал. Я с радостью одобрю PR с вашими правками.

**Comment by animkaTT** [comment]
Можно использовать тестовые отправления, у которых статус = "awaiting_deliver". Например отправление "25849584-0029-1". Доступы в тестовую среду указаны в документации https://cb-api.ozonru.me/apiref/ru/#t-title_sandbox
