### ISSUE TITLE
PHP Fatal error при 502 ответе озона

### ISSUE THREAD

**Issue by VampiRUS** [gam6itko/ozon-seller#30]
Озон отвечает 502 кодом и 
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
В итоге ошибка
PHP Fatal error: Uncaught RuntimeException: Invalid json error response: in /vendor/gam6itko/ozon-seller/src/Service/AbstractService.php:127

**Comment by gam6itko** [comment]
@VampiRUS такое происходит с каким-то конкретным запросом или иногда может произойти с любым?

**Comment by VampiRUS** [comment]
Озон падал.

**Comment by gam6itko** [comment]
Вместо `\RuntimeException` для ошибок без json body будет создаваться исключение `OzonSellerException`
