### ISSUE TITLE
Валидатор «съедает» наименование товара

### ISSUE THREAD

**Issue by mediaproduct** [gam6itko/ozon-seller#35]
В импорте товара /v2/product/import обрезается параметр name. В результате в Озон товар попадает без названия.
Конфиг валидатора product_validator_v2.php просится, чтобы его дополнили.

**Comment by gam6itko** [comment]
В [описании](https://api-seller.ozon.ru/apiref/ru/#t-title_product_import) не было информации `name`, но в примере оно присутствует. Я добавлю этот параметр, как необязательный

**Comment by gam6itko** [comment]
@mediaproduct исправлено в v0.5.4
