### ISSUE TITLE
can't get returns data from https://api-seller.ozon.ru/v2/returns/company/fbs

### ISSUE THREAD

**Issue by fengmiq** [gam6itko/ozon-seller#36]
![111](https://user-images.githubusercontent.com/43661323/118935305-f8bb3100-b97d-11eb-8549-2d71f4dd90a1.jpg)
![222](https://user-images.githubusercontent.com/43661323/118935312-f9ec5e00-b97d-11eb-8793-07485e17f22e.jpg)

**Comment by gam6itko** [comment]
example
```php
$svc = new ReturnsService($config, $adapter);
$result = $svc->company(
    PostingScheme::FBS,
    [
        'filter' => [
            'posting_number' => ['40350856-0024-1'],
        ],
    ]
);
```
