### ISSUE TITLE
image360

### ISSUE THREAD

**Issue by Artem163397** [gam6itko/ozon-seller#38]
Привет! Как мне в созданый товар добавить images360

**Comment by Artem163397** [comment]
??

**Comment by gam6itko** [comment]
Скорее всего нужно добавить элемент "images360" в массив при импорте товара
```php
$svc->import([
//properties
   'images360' => [
'img_url'
]
])
```

**Comment by gam6itko** [comment]
@Artem163397 ваша проблема решилась?

**Comment by Artem163397** [comment]
Да я решил без этого модуля в ручную запрос сделал
