### ISSUE TITLE
Service\V2\Posting\FbsService unfulfilledList ошибка, если не передать with

### ISSUE THREAD

**Issue by VampiRUS** [gam6itko/ozon-seller#39]
Если при вызове unfulfilledList не передать значение with, то озон не может распарсить такой json
`{"with":[],"status":["awaiting_packaging"],"sort_by":"updated_at","dir":"asc","offset":0,"limit":50}`
Ошибка:
Data: `[{"name":"cause","code":"","value":"json: cannot unmarshal array into Go value of type map[string]json.RawMessage","message":""}]`

если передать, то запрос будет таким
`{"with":{"barcodes":true},"status":["awaiting_packaging"],"sort_by":"updated_at","dir":"asc","offset":0,"limit":50}`
и всё норм

**Comment by gam6itko** [comment]
@VampiRUS v0.8.1
