### ISSUE TITLE
Изменения в методах

### ISSUE THREAD

**Issue by mrHeoH** [gam6itko/ozon-seller#4]
От Озона:
Мы запустили вторую версию API, где обновили методы получения списков заказов и их обработки. Она работает стабильнее и лучше оптимизирована.  Документация по новой версии:   для схемы «Отгрузка со склада продавца», для схемы «Отгрузка со склада Ozon». И важно: перейти на новую версию нужно до Нового года, так как после 9 января старая версия работать уже не будет.

**Comment by gam6itko** [comment]
Реализовано в 067e1b6c6d3584fe344e6e1cd4fdf0d3fbd4db0a, но к некоторым работе некоторых  методов на стороне OZON есть вопросы. Я протестирую на реальных заказах в течение декабря и сделаю релиз 0.2.0

**Comment by gam6itko** [comment]
https://packagist.org/packages/gam6itko/ozon-seller#v0.2.0
