### ISSUE TITLE
The interface request parameter language parameter is invalid

### ISSUE THREAD

**Issue by Ruiky** [gam6itko/ozon-seller#42]
for example:
https://api-seller.ozon.ru/v2/category/attribute
{
  "attribute_type": "ALL",
  "category_id": 0,
  "language": "EN"
}

After passing the request, I got Russian, not English

**Comment by gam6itko** [comment]
@Ruiky Looks like the  problem on Ozon site. I just wrote a ticket to Ozon tech support

**Comment by gam6itko** [comment]
Ответ от ТП

> Добрый день, уважаемый партнер.
Понимаю, что вам важно разобраться в данном вопросе.
К сожалению на данный момент английский язык недоступен.
Доступна возможность получать ответы только на русском.
Приносим извинения за эти неудобства.
Наши разработчики  в курсе, что такая проблема существует, задача на исправление работы метода, также есть.
К сожалению точных сроков назвать не можем, рекомендуем вам следить за новостями о работе API здесь: [https://docs.ozon.ru/api/seller/#tag/News]
Если у вас возникнут дополнительные вопросы, обращайтесь, будем рады вам помочь.
