### ISSUE TITLE
Undefined index: error

### ISSUE THREAD

**Issue by lapaliv** [gam6itko/ozon-seller#43]
Здравствуйте. Частенько получаем следующую ошибку:

`Undefined index: error at /var/www/vendor/gam6itko/ozon-seller/src/Service/AbstractService.php:146)`

Запрос:
```
{
    "method": "POST",
    "uri": "/v1/product/list",
    "body": {
        "page": 1,
        "page_size": 1000,
        "filter": {
            "visibility": "VISIBLE"
        }
    }
}
```

Ответ:
`{"code":7,"message":"Invalid Api-Key, please contact support","details":[]}`

**Comment by gam6itko** [comment]
Поправлю

**Comment by gam6itko** [comment]
@lapaliv можно проверять

**Comment by lapaliv** [comment]
Спасибо. Работает
