### ISSUE TITLE
primary_image в import и update

### ISSUE THREAD

**Issue by mediaproduct** [gam6itko/ozon-seller#44]
Поддержка Озона про /import сообщает:
> Добавили в запрос параметр primary_image — ссылка на главное изображение товара. Если у вас одно изображение, то его не нужно будет указывать в параметре images, а только в primary_image

Но правила валидации product_validator_v2.php не позволяют опустить параметр images.

Не смотря на то, что в документации озона предлагается указывать главное изображение первым в списке images, мы столкнулись с ошибкам обработки фотографий на стороне Озона. Поэтому нужно явно задавать главное в primary_image

**Comment by gam6itko** [comment]
@mediaproduct  https://github.com/gam6itko/ozon-seller/releases/tag/v0.8.5 проверяйте

**Comment by mediaproduct** [comment]
Спасибо за оперативность!
