### ISSUE TITLE
/v2/category/attribute 404

### ISSUE THREAD

**Issue by mediaproduct** [gam6itko/ozon-seller#45]
Перестал работать /v2/category/attribute — 404 page not found
Поддержка озона рекомендует перейти на /v3/category/attribute
«Метод устарел, убрали его из документации. Используйте /v3/category/attribute»

https://docs.ozon.ru/api/seller/#operation/CategoryAPI_GetCategoryAttributesV3

**Comment by gam6itko** [comment]
@mediaproduct Не совсем понимаю в чём проблема. 

Реализация метода `/v3/category/attribute` имеется
https://github.com/gam6itko/ozon-seller/blob/master/src/Service/V3/CategoryService.php

Ошибку при использовании  `/v2/category/attribute` выдаёт сам Озон. Я могу лишь только пометить этот метод как deprecated или вовсе удалить

**Comment by mediaproduct** [comment]
Да, всё верно. В озоне 404. Вопрос закрыт.
Спасибо.
