### ISSUE TITLE
Ошибка при вызове метода V3\Posting\FbsService::unfulfilledList без указания фильтра

### ISSUE THREAD

**Issue by downace** [gam6itko/ozon-seller#48]
Версия библиотеки v0.8.7

Вызов `\Gam6itko\OzonSeller\Service\V3\Posting\FbsService::unfulfilledList` без параметров формирует следующий запрос (заголовки опущены для краткости):

```http
POST /v3/posting/fbs/unfulfilled/list HTTP/1.1

{"with":{"analytics_data":false,"barcodes":false,"financial_data":false},"filter":[],"dir":"asc","offset":0,"limit":10}
```

Ответ:

```http
HTTP/1.1 400 Bad Request

{"code":3,"message":"proto: syntax error (line 1:83): unexpected token [","details":[]}
```

Полагаю, проблема в том, что при преобразовании в JSON пустой массив преобразуется в `[]` вместо `{}`.

Похожая проблема была в #40, там это решили добавлением дефолтных значений для некоторых полей фильтра (чтобы он никогда не был пустым).

**Comment by gam6itko** [comment]
@downace https://github.com/gam6itko/ozon-seller/releases/tag/v0.8.8 проверяйте

**Comment by gam6itko** [comment]
В 89f1d6c отчати решена проблема пустого объекта. Но возникла новая "the mismatch between cutoff & delivery date"

**Comment by gam6itko** [comment]
@downace ответ от поддержки

> Добрый день, уважаемый партнёр.
> Благодарим за вопрос.
> 
> 
> 
> Необходимо прописывать один из фильтров, cutoff или delivering_date.
> Пример корректного запроса: 
> 
> {
> "dir":"asc",
> "filter":
> 
> { "cutoff_from":"2021-10-24T14:15:22Z", "cutoff_to":"2021-11-24T14:15:22Z", "status":"awaiting_packaging" }
> 
> ,
> "limit":10,
> "offset":0,
> "with":
> 
> { "analytics_data":true, "barcodes":true, "financial_data":true }
> 
> }

**Comment by downace** [comment]
Принято, спасибо! Будем передавать правильные параметры.

Изначальная проблема возникла при тестировании, когда просто попробовали вызвать метод без параметров. Ошибка **the mismatch between cutoff & delivery date** чуть более понятна, чем **proto: syntax error...**
