### ISSUE TITLE
AbstractService.php выдает ошибку

### ISSUE THREAD

**Issue by xmonkx** [gam6itko/ozon-seller#49]
36 строка:

ErrorException
assert(): assert(null !== $requestFactory) failed

при этом версия файла https://github.com/gam6itko/ozon-seller/blob/0.4-x/src/Service/AbstractService.php работает стабильно

**Comment by gam6itko** [comment]
@xmonkx https://github.com/gam6itko/ozon-seller/releases/tag/v0.8.0 

начиная с версии v0.8 нужно предавать дополнительные аргумента
