### ISSUE TITLE
/v1/chat/list too slowly，can you help me

### ISSUE THREAD

**Issue by fengmiq** [gam6itko/ozon-seller#53]
Chat list（/v1/chat/list ） has too much data and is pulled too slowly. Can you provide change time parameters. It takes one hour to pull a store, and many stores can't be pulled at all,can you help me

**Comment by gam6itko** [comment]
@fengmiq You can use `page` and `page_size` query options to split result on chunks. It must speedup fetching of data.

```php
$svc = new ChatService($config, $client);
$chunk = $svc->list([
  'page' => $i,
  'page_size' => 100
]);
```

**Comment by gam6itko** [comment]
I'm closing it. no answer for too long
