### ISSUE TITLE
метод /v1/brand/company-certification/list еще реализован ?

### ISSUE THREAD

**Issue by skvarovski** [gam6itko/ozon-seller#57]
Здравствуйте,
Правильно ли я понял, что данный метод в топике у Вас еще не реализован?

ps. Пробую использовать Вашу библиотеку и получаю ошибку по таску, что импортируемый товар подлежит сертификации со ссылкой на данный метод, а быстрым поиском не нашёл в библиотеке.

**Comment by gam6itko** [comment]
скорее всего не рализован, можете сделать PR или подождать пока я добавлю

**Comment by skvarovski** [comment]
спасибо за ответ, надо подумать, если разберусь , то сделаю PR

**Comment by gam6itko** [comment]
@skvarovski проверяйте v0.8.16 

```php
use Gam6itko\OzonSeller\Service\V1\BrandService;

$svc = new BrandService();
$svc->companyCertificationList();
```
