### ISSUE TITLE
Получить комиссию Озона для подсчёта прибыли?

### ISSUE THREAD

**Issue by kirgus** [gam6itko/ozon-seller#6]
Есть необходимость считать реальную прибыль, для этого надо получать комиссию Озона.
В документации нет описания методов для получения комиссии.

Задавал вопрос, ответили, что метод есть. Может быть его включить в библиотеку:

```
POST /v1/product/list/price
{
  "filter": {
    "offer_id": [],
    "product_id": [],
    "visibility": "ALL"
  },
  "page": 1,
  "page_size": 100
}
Ответ:
{
  "result": {
    "items": [
      {
        "buybox_price": "string",
        "commission": {
          "percent": 0,
          "value": 0
        },
        "id": 0,
        "offer_id": "string",
        "old_price": "string",
        "premium_price": "string",
        "price": "string",
        "recommended_price": "string"
      }
    ],
    "total": 0
  }
}
```

**Comment by gam6itko** [comment]
Спасибо. Скоро добавим

**Comment by gam6itko** [comment]
@kirgus при запросе сервер возвращает ошибку `Invalid JSON payload`. У вас получалось сделать реальный запрос к серверу? Можете предоставить рабочий запрос?

**Comment by kirgus** [comment]
Нужен хотя бы пустой JSON передать.


![image](https://user-images.githubusercontent.com/47494681/70928946-14acfb80-2043-11ea-97d9-3047f75fe168.png)

**Comment by gam6itko** [comment]
Пока документации по тому как правильно задать поле `filter`нет, этот параметр не работает. Вы можете протестировать работу функции в обновившись до 0.2@dev
