### ISSUE TITLE
Вопрос по ProductService V3

### ISSUE THREAD

**Issue by nb-nortus** [gam6itko/ozon-seller#60]
Добрый день, подскажите, будет ли реализован в ближайшее время в вашей библиотеки ProductService V3?
С 30 августа 2022 года Ozon отключает часть методов, и в списке по ссылке [Отключение методов](https://docs.ozon.ru/api/seller/?xnpe_tifc=4.BubdbZb.Ls4kHJ4DhuhMpWhFWLV9Q3RC8NVuechYBNRZ8ZEMX7Ofe.h.xjOFbDxFV84fbD&utm_source=exponea&utm_campaign=MPCOM-6633-api-none&utm_medium=email#section/Otklyuchenie-metodov) есть следующие строки:
Информация о количестве остатков -> /v3/product/info/stocks
Получить описание характеристик товара -> /v3/products/info/attributes
Методы предыдущих версий будут не доступны.

**Comment by gam6itko** [comment]
Если нужно, то добавлю, на этой или следующей неделе

**Comment by nb-nortus** [comment]
> Если нужно, то добавлю, на этой или следующей неделе

Да, был бы Вам за это очень благодарен)

**Comment by gam6itko** [comment]
@nb-nortus Проверяёте v0.8.16
