### ISSUE TITLE
\Gam6itko\OzonSeller\Service\V2\ProductService::infoStocks(). Obsolete method cannot be used

### ISSUE THREAD

**Issue by SergeyBarabash** [gam6itko/ozon-seller#61]
05.09.2022 при использовании метода `\Gam6itko\OzonSeller\Service\V2\ProductService::infoStocks()` API Ozon выдал ошибку `Obsolete method cannot be used`. У них уже реализован этот метод версии V3, а в библиотеке его нет.

**Comment by gam6itko** [comment]
Добавлен в [8ff68b1](https://github.com/gam6itko/ozon-seller/commit/8ff68b1f4e9ebcb9c18283a43910a16f55777f4e)

**Comment by downace** [comment]
> Добавлен в [8ff68b1](https://github.com/gam6itko/ozon-seller/commit/8ff68b1f4e9ebcb9c18283a43910a16f55777f4e)

Не могу найти этот метод в актуальной версии...

В коде V1/ProductService есть пометка `@deprecated use V3\ProductService::infoStocks`, но этот метод в V3 отсутствует.

**Comment by gam6itko** [comment]
@downace Есть в v2. Но скоро я добавлю поддержку для v3
