### ISSUE TITLE
Некорректная обработка статусов ответа

### ISSUE THREAD

**Issue by holdmann** [gam6itko/ozon-seller#62]
Со вчера начали сыпаться эксепшены

```
Client error: POST `http://api-seller.ozon.ru/v3/posting/fbs/list` resulted in a `405 Method Not Allowed` response
```

В AbstractService идет проверка только содержимого контента, но в данном случае нужно проверять статус, тк боди пустое. 

Соответственно на выходе получаем пустой эксепшен

```
Gam6itko\OzonSeller\Exception\OzonSellerException Object
(
    [details:protected] => Array
        (
        )

    [message:protected] => 
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/vhosts/***/local/php_interface/vendor/gam6itko/ozon-seller/src/Service/AbstractService.php
    [line:protected] => 146
    [trace:Exception:private] => Array
        (
)
```

![image](https://user-images.githubusercontent.com/2150007/190619429-1f31a4de-3ac3-45a8-a1fe-48c7d1283fba.png)

**Comment by gam6itko** [comment]
Сейчас проверил этот метод, на стороне озона он работает.

Ты имеещь в виду что выбросится excption с пустым сообщением и нужно хотя бы писать статус?

**Comment by gam6itko** [comment]
Добавил собщение по-умолчанию
