### ISSUE TITLE
can't use api:https://api-seller.ozon.ru/v1/product/import-by-sku,return error:Техническая ошибка

### ISSUE THREAD

**Issue by fengmiq** [gam6itko/ozon-seller#68]
api：
https://api-seller.ozon.ru/v1/product/import-by-sku
param：
```json
{
  "offer_id": "82605303223525",
  "old_price": "6158",
  "price": "3658",
  "premium_price": "3600",
  "currency_code": "CNY",
  "sku": 826053031,
  "vat": "0"
}
```
result：
```json
{
  "result": {
    "items": [
      {
        "offer_id": "82605303223525",
        "product_id": 0,
        "status": "failed",
        "errors": [
          {
            "code": "bad_request_error",
            "field": "",
            "attribute_id": 0,
            "state": "new",
            "level": "error",
            "description": "Техническая ошибка",
            "optional_description_elements": [],
            "attribute_name": "",
            "message": "Неверно указана валюта"
          }
        ]
      }
    ],
    "total": 1
  }
}
```

**Comment by gam6itko** [comment]
@fengmiq Эта ошибка на стороне ozon. Скорее всего вы передали неправильные данные.

**Comment by fengmiq** [comment]
> @fengmiq Эта ошибка на стороне ozon. Скорее всего вы передали неправильные данные.

Те же параметры, локальный магазин нормальный, а вот трансграничный магазин не тот, можете мне проверить? Спасибо!

**Comment by gam6itko** [comment]
@fengmiq  Я оформил json  в вашем посте и вижу что есть еще пояснение к ошибке "Неверно указана валюта"

**Comment by fengmiq** [comment]
@gam6itko Я попробовал другие валюты, но те же параметры, чтобы попросить местные магазины, это нормально, трансграничные магазины должны настроить какие - то специальные параметры?

**Comment by jrsTao** [comment]
> @gam6itko Я попробовал другие валюты, но те же параметры, чтобы попросить местные магазины, это нормально, трансграничные магазины должны настроить какие - то специальные параметры?

Здравствуйте, я столкнулся с той же проблемой, вы решили ее позже ？
