### ISSUE TITLE
Устарели методы /v3/posting/fbs/ship

### ISSUE THREAD

**Issue by apasov** [gam6itko/ozon-seller#83]
https://docs.ozon.ru/api/seller/#section/9-fevralya-2024

Озон с 9 февраля выдает ошибку по методам `/v3/posting/fbs/ship` и `/v3/posting/fbs/ship/package`

**Comment by gam6itko** [comment]
@apasov Вы предлагаете их удалить, пометить как deprecated или реализовать поддержку альтернативных методов?

**Comment by apasov** [comment]
@gam6itko Они не просто deprecated. Они уже вышли из этой стадии и не работают вообще. Поэтому, думаю надо удалить их польностью. С 9 февраля работают только методы `/v4/posting/fbs/ship` и `/v4/posting/fbs/ship/package`. Их я и предлагаю реализовать. Они не альтернативные, им альтернативы нет, они единственные рабочие на данный момент, насколько я понимаю. Все остальные версии, кроме 4-ой, вообще удалены из документации.
https://docs.ozon.ru/api/seller/#operation/PostingAPI_ShipFbsPostingV4
